"""Recreating migrations

Revision ID: d48d05dde36c
Revises: 
Create Date: 2025-03-06 09:36:49.307362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48d05dde36c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dist_obituary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.String(length=50), nullable=True),
    sa.Column('death_date', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('obituary_url', sa.String(length=255), nullable=False),
    sa.Column('family_information', sa.Text(), nullable=True),
    sa.Column('donation_information', sa.Text(), nullable=True),
    sa.Column('is_alumni', sa.Boolean(), nullable=True),
    sa.Column('funeral_home', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obituary_url')
    )
    with op.batch_alter_table('obituary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('funeral_home', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obituary', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('funeral_home')
        batch_op.drop_column('name')

    op.drop_table('dist_obituary')
    # ### end Alembic commands ###
